name: beacon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  device_info_plus: ^12.2.0
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_p2p_connection: ^3.0.3
  permission_handler: ^11.4.0
  path_provider: ^2.1.2
  sqflite_sqlcipher: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
